#
# Transmission Docker Image
# by Kung@ACGunion
#
# sshd service
# supervisor service
# Transmission Daemon
# PHP&H5AI
#     on CentOS 6.6
#         Base on treasureboat/ssh
#

FROM treasureboat/ssh

EXPOSE 22
EXPOSE 80
EXPOSE 443
EXPOSE 5555
EXPOSE 8080
EXPOSE 23
EXPOSE 21
EXPOSE 25
