FROM 1and1internet/ubuntu-16-apache-php-7.1

#Baes on 1&1Internet with PHP7.1 on it That will run for yetishare

MAINTAINER Kunger <fssbbskefu@gmail.com>

#Run system repo update

RUN apt update -y && apt upgrade -y

#Install FFmpeg

RUN apt install ffmpeg -y

#That run with Apache so expose the port

EXPOSE 8080

